#!/usr/bin/env python3
"""
Generate a 1-page threat intelligence summary report (Markdown) from a scored
IOC dataset, and optionally a Splunk-compatible lookup CSV.

Usage:
    python reports/generate_report.py                 # uses data/iocs.json
    python reports/generate_report.py --demo           # uses data/demo_iocs.json
    python reports/generate_report.py --splunk-csv lookup.csv
"""

import argparse
import csv
import json
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from scoring import score_ioc, classify  # noqa: E402


def load(demo):
    path = ROOT / "data" / ("demo_iocs.json" if demo else "iocs.json")
    iocs = json.loads(path.read_text())["iocs"]
    for ioc in iocs:
        ioc.setdefault("risk_score", score_ioc(ioc))
        ioc.setdefault("severity", classify(ioc["risk_score"]))
    iocs.sort(key=lambda x: x["risk_score"], reverse=True)
    return iocs


def markdown_report(iocs):
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    sev = Counter(i["severity"] for i in iocs)
    types = Counter(i["type"] for i in iocs)
    sources = Counter()
    for i in iocs:
        for s in i["source"].split(", "):
            sources[s] += 1

    lines = [
        "# Threat Intelligence Daily Summary",
        "",
        f"**Generated:** {now}  ",
        f"**Total indicators:** {len(iocs)}  ",
        f"**Severity:** Critical {sev.get('Critical',0)} · High {sev.get('High',0)} · "
        f"Medium {sev.get('Medium',0)} · Low {sev.get('Low',0)}",
        "",
        "## IOC Type Distribution",
        "",
        "| Type | Count |", "|------|-------|",
    ]
    lines += [f"| {t} | {n} |" for t, n in types.most_common()]
    lines += ["", "## Feed Source Breakdown", "", "| Source | Count |", "|--------|-------|"]
    lines += [f"| {s} | {n} |" for s, n in sources.most_common()]

    lines += ["", "## Top 10 High-Risk Indicators", "",
              "| Risk | Severity | Type | Indicator | Source | Tags |",
              "|------|----------|------|-----------|--------|------|"]
    for i in iocs[:10]:
        tags = ", ".join(i.get("tags", [])[:3])
        ind = i["ioc"] if len(i["ioc"]) <= 60 else i["ioc"][:57] + "..."
        lines.append(f"| {i['risk_score']} | {i['severity']} | {i['type']} | "
                     f"`{ind}` | {i['source']} | {tags} |")

    lines += ["", "---",
              "_Generated by the Threat Intelligence Platform "
              "(Kuldeep J. Jotaniya). Risk score = 0.5·VT + 0.3·AbuseIPDB + "
              "0.2·recency, scaled 1-10._", ""]
    return "\n".join(lines)


def splunk_lookup_csv(iocs, path):
    """Write a Splunk-compatible lookup table (one row per IOC)."""
    fields = ["ioc", "type", "source", "risk_score", "severity",
              "vt_detection_ratio", "abuseipdb_score", "first_seen", "tags"]
    with open(path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        for i in iocs:
            row = dict(i)
            row["tags"] = "|".join(i.get("tags", []))
            writer.writerow(row)


def main():
    parser = argparse.ArgumentParser(description="Generate threat intel report")
    parser.add_argument("--demo", action="store_true")
    parser.add_argument("--out", default=str(Path(__file__).parent / "sample_threat_report.md"))
    parser.add_argument("--splunk-csv", help="Also write a Splunk lookup CSV here")
    args = parser.parse_args()

    iocs = load(args.demo)
    Path(args.out).write_text(markdown_report(iocs))
    print(f"Wrote report: {args.out}")
    if args.splunk_csv:
        splunk_lookup_csv(iocs, args.splunk_csv)
        print(f"Wrote Splunk lookup: {args.splunk_csv}")


if __name__ == "__main__":
    main()
